// Module included in the following assemblies:
//
// * assemblies/assembly-aws-policy-ccs.adoc

[id="con-aws-policy-provisioned_{context}"]
= Provisioned AWS Infrastructure

[role="_abstract"]
This is an overview of {product-title} specific deployments. For a more detailed listing of all AWS components provisioned, you can refer to the link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/[OpenShift Container Platform documentation].

== EC2 instances

AWS EC2 instances are required for deploying the control plane and data plane functions of {product-title} in the AWS public cloud.

- Three m5.xlarge minimum (Masters Nodes)
- Three m5.xlarge minimum (Infrastructure Nodes)
- Four m5.xlarge minimum but highly variable (Compute Nodes)

== EBS storage

Amazon EBS block storage is used for both local node storage and persistent volume storage.

Volume requirements for each EC2 instance:

- Master Volume
* Size: 350GB
* Type: io1
* Input/Output Operations Per Second: 1000

- Infrastructure Volume
* Size: 300GB
* Type: gp2
* Input/Output Operations Per Second: 100

- Compute Volume
* Size: 300GB
* Type: gp2
* Input/Output Operations Per Second: 100


== Elastic load balancers

Up to two Network Elastic Load Balancers (ELBs) for API and up to two Classic ELBs for application router. See here for more details on link:https://aws.amazon.com/elasticloadbalancing/features/#Details_for_Elastic_Load_Balancing_Products[ELBs].


== S3 storage
The image registry and EBS volume snapshots are backed by AWS S3 storage. Pruning of resources is performed regularly to optimize S3 usage and cluster performance.

[NOTE]
====
Two buckets are required with a typical size of 2TB each.
====

== VPC
Customers should expect to see one VPC per cluster. Additionally, the VPC will need the following configurations:

- Subnets
* Two subnets for a cluster with a single availability zone is preferred
* Six subnets for a cluster with mutltiple availability zones is preferred
- Router Tables
* One router table per private subnet and one additional table per cluster
- Internet Gateways
* One per cluster
- NAT Gateways
* One per public subnet

== Security groups

AWS security groups are associated with EC2 instances and Elastic Load Balancers and provide security at the protocol and port access level. Each security group, working much the same way as a firewall, contains a set of rules that filter traffic coming into and out of an EC2 instance. You must ensure the ports required for the OpenShift installation are open on your network and configured to allow access between hosts.

[cols="2a,2a,2a,2a",options="header"]
|===

|Group
|Type
|IP Protocol
|Port range


.4+|MasterSecurityGroup
.4+|`AWS::EC2::SecurityGroup`
|`icmp`
|`0`

|`tcp`
|`22`

|`tcp`
|`6443`

|`tcp`
|`22623`

.2+|WorkerSecurityGroup
.2+|`AWS::EC2::SecurityGroup`
|`icmp`
|`0`

|`tcp`
|`22`


.2+|BootstrapSecurityGroup
.2+|`AWS::EC2::SecurityGroup`

|`tcp`
|`22`

|`tcp`
|`19531`

|===
