// Module included in the following assemblies:
//
// * assemblies/creating-your-cluster.adoc

[id="creating-your-cluster_{context}"]
= Configuring an OpenID identity provider

Configure an OpenID identity provider to integrate with an OpenID Connect
identity provider using an
link:http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[Authorization Code Flow].

[IMPORTANT]
====
The Authentication Operator in {product-title} requires that the configured
OpenID Connect identity provider implements the
link:https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery]
specification.
====

By default, the OpenID scope is requested. If required, extra scopes can be
specified in the *Additonal scopes* field.

Claims are read from the JWT `id_token` returned from the OpenID identity
provider and, if specified, from the JSON returned by the Issuer URL.

At least one claim must be configured to use as the user's identity.

You can also indicate which claims to use as the user's preferred user name,
display name, and email address. If multiple claims are specified, the first one
with a non-empty value is used. The standard claims are:

[horizontal]
`preferred_username`:: The preferred user name when provisioning a user. A
shorthand name that the user wants to be referred to as, such as `janedoe`. Typically
a value that corresponding to the user's login or username in the authentication
system, such as username or email.
`email`:: Email address.
`name`:: Display name.

See the
link:http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims[OpenID claims documentation]
for more information.

.Procedure

To configure an OpenID identity provider for your {product-title} cluster:

. Navigate to the *Clusters* page and select the cluster you need to configure identity providers for.

. Click the *Access control* tab.
Note: You can also click the *AddOauth configuration* link in the warning message displayed after cluster creation to configure your identity providers.

. Click *Add identity provider*.

. Select *OpenID* from the drop-down menu.

. Enter a unique name for the identity provider. This name cannot be changed later. An *OAuth callback URL* is automatically generated in the provided field.

. Select a mapping method from the drop-down menu. *Claim* is recommended in most cases.

. Enter a *Client ID* and *Client secret*.

. Enter an *Issuer URL*. This is the URL that the OpenID provider asserts as the Issuer Identifier. It must use the https scheme with no URL query parameters or fragment.

. Enter an *Email* attribute whose value should be used as the email address. Click *Add more* to add multiple email attributes.

. Enter a *Name* attribute whose value should be used as the preferred username. Click *Add more* to add multiple preferred usernames.

. Enter a *Preferred username* attribute whose value should be used as the display name. Click *Add more* to add multiple display names.

. Optional: Click *Show advanced Options* to add a certificate authority (CA) file to your OpenID identity provider.

. Optional: Under the advanced options, you can *Additional scopes*.

. Click *Confirm*.


The configured identity provider is now visible on the
 *Access control* tab of the *Clusters* page.
