// Module included in the following assemblies:
//
// * assemblies/creating-your-cluster.adoc

[id="creating-your-cluster_{context}"]
= Creating an AWS CCS Cluster

You can create a cluster with a Customer Cloud Subscription (CCS). With this subscription option, the cluster will be provisioned in an AWS account owned by you or your company. This allows you to pay AWS directly for public cloud costs, leveraging your existing relationship.

To create your {product-title} AWS CSS cluster:

.Prerequisites
- Your AWS account has no services deployed in it.
- Your AWS account has the necessary quotas and limits to support the desired cluster size.
- An IAM user called `osdCcsAdmin` exists with the AdministratorAccess policy.
- An Organization Service Control Policy (SCP) is set up.
- It is recommended that you have at least *Business Support* from AWS.

.Procedure

. Log in to link:https://cloud.redhat.com/openshift[cloud.redhat.com/openshift].

. Click *Create Cluster* -> *Red Hat OpenShift Dedicated*.

. Select *AWS* as your infrastructure provider.

. Select *Customer cloud subscription*. An informational dialogue window will open. Review the prerequisites for installing an AWS CCS cluster and click *Close*.

. Enter your *AWS account ID*.

. Enter your *AWS access key ID* and *AWS secret access key* to input your AWS IAM user credentials.
  Note: Revoking these credentials in AWS will result in a loss of access to any cluster created with these credentials.

. Optional: You can select *Bypass AWS Service Control Policy (SCP) checks*. Some AWS Service Control Policies will cause installation to fail, even if the credentials have the correct permissions. Disabling SCP checks allows installation to proceed. The SCP will still be enforced even if the checks are bypassed.

. Enter your *Cluster name*.

. Select a *Region* and choose either a *Single zone* or *Multizone* availability.

. Select your *Compute node instance type* and the *Compute node count (per zone)*. After your cluster is created, you can change the number of compute nodes in your cluster, but you can not change the worker node instance type.

. The *Basic* Network configuration is selected by default. This setting creates a new VPC for your cluster using the default values.
If you want to configure your networking IP ranges or set your cluster privacy, select *Advanced*. The
following are the default ranges available for your networking IP ranges:

.. Node CIDR: 10.0.0.0/16

.. Service CIDR: 172.30.0.0/16

.. Pod CIDR: 10.128.0.0/14

.. Host Prefix: /23
+
[IMPORTANT]
====
CIDR configurations cannot be changed later. Confirm your selections with your network administrator before proceeding.
====
+
[IMPORTANT]
====
If the cluster privacy is set to *Private*, you will not be able to access your cluster until you configure private connections in your cloud provider.
====

. Click *Create cluster*. The cluster creation process begins and will take about 30-40 minutes to complete.


The *Installing cluster* heading, under the *Overview* tab, will indicate the cluster is installing and where it is in the process. You can also view the installation logs from this heading. The *Status*
indicator under the *Details* heading will indicate when your cluster is *Ready* for use.
