// Module included in the following assemblies:
//
// * assemblies/osd-policy-ccs-requirements.adoc

[id="gcp-policy-ccs_{context}"]
= Requirements for Google Cloud

Red Hat recommends the usage of a Google Cloud project, managed by the customer, to organize all of your Google Cloud resources. A project consists of a set of users; a set of APIs; and billing, authentication, and monitoring settings for those APIs.

It is a best practice for the {product-title} CCS cluster to be hosted in a Google Cloud project within a Google Cloud organization. The Organization resource is the root node of the Google Cloud resource hierarchy and all resources that belong to an organization are grouped under the organization node. An IAM Service Account with certain roles attached is created and applied to the Google Cloud project. When you make calls to the API, you typically provide service account keys for authentication. Each service account is owned by a specific project, but service accounts may be provided roles to access resources for other projects. Red Hat SRE will not have any control over the Service Account within the Google Cloud project.


== Customer procedure

1. link:https://cloud.google.com/resource-manager/docs/creating-managing-projects[Create a Google Cloud project] to host the {product-title} cluster. Note: The project name must be 10 characters or less.
2. link:https://cloud.google.com/service-usage/docs/enable-disable#enabling[Enable ] the following required APIs in the project that hosts your {product-title} cluster.
+
.Required API services
[cols="2a,3a",options="header"]
|===
|API service |Console service name

ifdef::template[]
|Cloud Deployment Manager V2 API
|`deploymentmanager.googleapis.com`
endif::template[]

|Compute Engine API
|`compute.googleapis.com`

|Google Cloud APIs
|`cloudapis.googleapis.com`

|Cloud Resource Manager API
|`cloudresourcemanager.googleapis.com`

|Google DNS API
|`dns.googleapis.com`

|IAM Service Account Credentials API
|`iamcredentials.googleapis.com`

|Identity and Access Management (IAM) API
|`iam.googleapis.com`

|Service Management API
|`servicemanagement.googleapis.com`

|Service Usage API
|`serviceusage.googleapis.com`

|Google Cloud Storage JSON API
|`storage-api.googleapis.com`

|Cloud Storage
|`storage-component.googleapis.com`

|===

3. Within the Google Cloud project, you must create an `osdCcsAdmin` IAM Service Account user with the following roles attached:
+

[cols="2a,3a",options="header"]
|===

|Role|Console role name


|DNS Administrator
|`roles/dns.admin`

|Organization Policy View
|`cloudapis.googleapis.com`

|Cloud Resource Manager API
|`cloudresourcemanager.googleapis.com`

|Google DNS API
|`dns.googleapis.com`

|IAM Service Account Credentials API
|`iamcredentials.googleapis.com`

|Identity and Access Management (IAM) API
|`iam.googleapis.com`

|Service Management API
|`servicemanagement.googleapis.com`

|Service Usage API
|`serviceusage.googleapis.com`

|Google Cloud Storage JSON API
|`storage-api.googleapis.com`

|Cloud Storage
|`storage-component.googleapis.com`

|===

- Organization Policy View
- Owner
Project Deleter
Project IAM Admin
Service Management Admin
Service Usage Admin
Storage Admin
4. Add toles to SA
5. Create key for SA


create project
Project must be 10 chars or less!  If not, the openshift-installer will fail.
Add IAM service account
in GCP Console: IAM -> Service Accounts
"+Create Service Account"
Add name, description
Add the following roles to the the new SA:
Project Billing Manager
DNS Administrator
Organization Policy View
Owner
Organization Admin
Project Deleter
Project IAM Admin
Service Management Admin
Service Usage Admin
Storage Admin
Create a key for the SA
in GCP Console: IAM -> Service Accounts -> SA Created -> Add Key -> Create New Key
Select JSON
Save key (will be a text file that is json).
This JSON file will be uploaded OCM


DNS Administrator
Organization Policy View
Owner
Project Deleter
Project IAM Admin
Service Management Admin
Service Usage Admin
Storage Admin

= Red Hat managed Google Cloud resources

== IAM
