:_module-type: CONCEPT
// Module included in the following assemblies:
//
// * assemblies/configuring-the-monitoring-stack.adoc

[id="support-considerations_{context}"]
= Support considerations for monitoring

[role="_abstract"]
The following modifications are explicitly not supported:

* *Creating additional `ServiceMonitor`, `PodMonitor`, and `PrometheusRule` objects in the `openshift-&#42;`, and `kube-&#42;` projects.*
* *Modifying any resources or objects deployed in the `openshift-monitoring`project.* The resources created by the {product-title} monitoring stack are not meant to be used by any other resources, as there are no guarantees about their backward compatibility.
+
[NOTE]
====
The Alertmanager configuration is deployed as a secret resource in the `openshift-monitoring` project. Configuring routes for your own alerts is not supported and there are no exceptions.
====
+
* *Modifying resources of the stack.* The {product-title} monitoring stack ensures its resources are always in the state it expects them to be. If they are modified, the stack will reset them.
* *Deploying user-defined workloads to `openshift-&#42;`, and `kube-&#42;` projects.* These projects are reserved for Red Hat provided components and they should not be used for user-defined workloads.
* *Modifying the monitoring stack Grafana instance.*
* *Installing custom Prometheus instances on {product-title}.*
* *Enabling symptom based monitoring by using the `Probe` custom resource definition (CRD) in Prometheus Operator.*
