// Module included in the following assemblies:
//
// * assemblies/configuring-egress-firewall.adoc

[id="nw-networkpolicy-create_{context}"]
= Creating an egress firewall policy object

As a cluster administrator, you can create an egress firewall policy object for a project.

[IMPORTANT]
====
If the project already has an {kind} object defined, you must edit the existing policy to make changes to the egress firewall rules.
====

.Prerequisites

* A cluster that uses the {cni} default Container Network Interface (CNI) network provider plug-in.
* Install the OpenShift CLI (`oc`).
* You must log in to the cluster as a cluster administrator.

.Procedure

. Create a policy rule:
.. Create a `<policy_name>.yaml` file where `<policy_name>` describes the egress
policy rules.
.. In the file you created, define an egress policy object.

. Enter the following command to create the policy object. Replace `<policy_name>` with the name of the policy and `<project>` with the project that the rule applies to.
+
[source,terminal]
----
$ oc create -f <policy_name>.yaml -n <project>
----
+
In the following example, a new {kind} object is created in a project named `project1`:
+
[source,terminal]
----
$ oc create -f default.yaml -n project1
----
+
.Example output
[source,terminal,subs="attributes"]
----
{obj} created
----

. Optional: Save the `<policy_name>.yaml` file so that you can make changes later.
