// Module included in the following assemblies:
//
// * assemblies/configuring-egress-firewall.adoc


[id="nw-egressnetworkpolicy-object_{context}"]
= {kind} custom resource (CR) object

You can define one or more rules for an egress firewall. A rule is either an `Allow` rule or a `Deny` rule, with a specification for the traffic that the rule applies to.

The following YAML describes an {kind} CR object:

.{kind} object
[source,yaml,subs="attributes+"]
----
apiVersion: {api}
kind: {kind}
metadata:
spec:
  egress: <2>
    ...
----

<2> A collection of one or more egress network policy rules as described in the following section.

[id="egressnetworkpolicy-rules_{context}"]
== {kind} rules

The following YAML describes an egress firewall rule object. The `egress` stanza expects an array of one or more objects.

// - OVN-Kubernetes does not support DNS
// - OpenShift SDN does not support port and protocol specification

.Egress policy rule stanza

ifdef::ovn[]
[source,yaml]
----
egress:
- type: <type> <1>
  to: <2>
    cidrSelector: <cidr> <3>
    ports: <4>
      ...
----
<1> The type of rule. The value must be either `Allow` or `Deny`.

<2> A stanza describing an egress traffic match rule.

<3> An IP address range in CIDR format.

<4> Optional: A stanza describing a collection of network ports and protocols for the rule.

.Ports stanza
[source,yaml]
----
ports:
- port: <port> <1>
  protocol: <protocol> <2>
----
<1> Optional: A network port, such as `80` or `443`.

<2> Optional: A network protocol. If specified, the value must be either `TCP`, `UDP`, or `SCTP`. If not specified, the rule matches all TCP, UDP, and SCTP traffic.
endif::ovn[]

[id="egressnetworkpolicy-example_{context}"]
== Example {kind} CR objects

The following example defines several egress firewall policy rules:

[source,yaml,subs="attributes+"]
----
apiVersion: {api}
kind: {kind}
metadata:
  name: default
spec:
  egress: <1>
  - type: Allow
    to:
      cidrSelector: 1.2.3.0/24
ifdef::openshift-sdn[]
  - type: Allow
    to:
      dnsName: www.example.com
endif::openshift-sdn[]
  - type: Deny
    to:
      cidrSelector: 0.0.0.0/0
----
<1> A collection of egress firewall policy rule objects.

ifdef::ovn[]
The following example defines a policy rule that denies traffic to the host at the `172.16.1.1` IP address, if the traffic is using either the TCP protocol and destination port `80` or any protocol and destination port `443`.

[source,yaml,subs="attributes+"]
----
apiVersion: {api}
kind: {kind}
metadata:
  name: default
spec:
  egress:
  - type: Deny
    to:
      cidrSelector: 172.16.1.1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
----
endif::ovn[]

ifdef::kind[]
:!kind:
endif::[]
ifdef::api[]
:!api:
endif::[]
ifdef::ovn[]
:!ovn:
endif::[]
ifdef::openshift-sdn[]
:!openshift-sdn:
endif::[]
