// Module included in the following assemblies:
//
// * assemblies/configuring-egress-firewall.adoc

[id="nw-egressnetworkpolicy-about_{context}"]
= How an egress firewall works in a project

As a cluster administrator, you can use an _egress firewall_ to
limit the external hosts that some or all Pods can access from within the
cluster. An egress firewall supports the following scenarios:

- A Pod can only connect to internal hosts and cannot initiate connections to
the public Internet.
- A Pod can only connect to the public Internet and cannot initiate connections
to internal hosts that are outside the {product-title} cluster.
- A Pod cannot reach specified internal subnets or hosts outside the {product-title} cluster.
- A Pod can connect to only specific external hosts.

For example, you can allow one project access to a specified IP range but deny the same access to a different project. Or you can restrict application developers from updating from Python pip mirrors, and force updates to come only from approved sources.

You configure an egress firewall policy by creating an {kind} custom resource (CR) object. The egress firewall matches network traffic that meets any of the following criteria:

- An IP address range in CIDR format


[WARNING]
====
Egress firewall rules do not apply to traffic that goes through routers. Any user with permission to create a Route CR object can bypass egress firewall policy rules by creating a route that points to a forbidden destination.
====

[id="limitations-of-an-egress-firewall_{context}"]
== Limitations of an egress firewall

An egress firewall has the following limitations:

* No project can have more than one {kind} object.

* A maximum of one {Kind} object with a maximum of 50 rules can be defined per project.

Violating any of these restrictions results in a broken egress firewall for the project, and may cause all external network traffic to be dropped.

[id="policy-rule-order_{context}"]
== Matching order for egress firewall policy rules

The egress firewall policy rules are evaluated in the order that they are defined, from first to last. The first rule that matches an egress connection from a Pod applies. Any subsequent rules are ignored for that connection.
