// Module included in the following assemblies:
//
// * assemblies/config-aws-private-connections.adoc

[id="config-aws-private-connections_{context}"]
= Configuring AWS infrastructure access

Before you can configure access to an AWS infrastructure, you will need to set up IAM permissions in your AWS account and grant the IAM role from the OpenShift Cluster Manager (OCM).

.Procedure


. Log in to your AWS account. If necessary, you can create a new AWS account by following the link:https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/[AWS documentation].

. Create an IAM user with `STS:AllowAssumeRole` permissions within the AWS account.

.. Open the IAM dashboard of the AWS Management Console.

.. In the *Policies* section, click *Create Policy*.

.. Select the `JSON` tab and replace the existing text with the following:

+
[source,json]
----
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "*"
        }
    ]
  }
----

.. Click *Review Policy*.

.. Provide an appropriate name and description, then click *Create Policy*.

.. In the *Users* section, click *Add user*.

.. Provide an appropriate user name.

.. Select *AWS Management Console access* and other roles as needed.

.. Adjust the password requirements as necessary for your organization, then click *Next: Policy*.

.. Click the *Attach existing policies directly* option.

.. Search for and check the policy created in previous steps.

+
[NOTE]
====
It is not recommended to set a permissions boundary.
====

.. Click *Next: Tags*, then click *Next: Review*. Confirm the configuration is correct.

.. Click *Create user*, then click *Close* on the success page.

. Gather the IAM user's Amazon Resource Name (ARN). The ARN will have the following format: `arn:aws:iam::000111222333:user/username`.

. Open the {product-title} Cluster Manager in your browser and select the cluster you want to allow AWS infrastructure access.

. Select the *Access control* tab, and scroll to the *AWS Infrastructure Access* section.

. Sign in to your AWS account with your Account ID or alias, IAM user name, and password.

. Copy the AWS OSD Console URL to your clipboard.

. In a new browser tab, paste the AWS OSD Console URL that will be used to route to the AWS Switch Role page.

. Your account number and role will be filled in already. Choose a display name if necessary, then click *Switch Role*. You will now see *VPC* under *Recently visited services*.

. Return to OCM and paste the AWS IAM ARN and select *Network Management* or *Read-only* permissions, then click *Grant role*.
