// Module included in the following assemblies:
//
// * assemblies/account-setup.adoc

[id="account-setup_{context}"]
= Creating a Red Hat account

To create your Red Hat account:

. Navigate to link:https://www.redhat.com/en[redhat.com]

. Click the *Log in* icon in the upper toolbar.

. Click *Register now*.

. Select your *Account type*.

- *Corporate*- A corporate Red Hat account allows a set of users to centrally purchase or administer systems within a corporate organization (system administrators, purchasing agents, IT management, etc.)
- *Personal*- A personal Red Hat account is for purchasing or administering your own personal systems.

. Create your Red Hat login user ID.

. Enter your email address.

. Enter a password and confirm the password. Your password must be at least 8 charcters long.

. Enter your  *Company* and *Title* information.

. Enter your *Contact Information* in the provided fields.

. Click *Submit*. You'll be redirected to the login page where you can immediately sign in. A confirmation email will be sent to the email you provided.


= Accessing your Red Hat account

To access your Red Hat account:

. From link:https://www.redhat.com/en[redhat.com], click
 the *Log in* icon in the upper toolbar and enter your credentials.

Once logged in, you can now access various Red Hat services.
You can access your account and log in, or log out, in the upper toolbar of any page you access.
It is recommended, for your security, that you log out when you have finished using your Red Hat services.
