// Module included in the following assemblies:
//
// * assemblies/osd_process_security.adoc

[id="osd_policy_change_management_{context}"]
= Change management
Cluster changes are initiated in one of two ways:

1. A customer initiates changes through self-service capabilities like cluster deployment, worker node scaling, and cluster deletion.
2. SRE initiates a change through Operator-driven capabilities like configuration, upgrade, patching, or configuration changes.

Change history is captured in the Cluster History section in OpenShift Cluster Manager (OCM) Overview tab and is available to customers. This includes logs from the following changes:

- Adding or removing identity providers
- Adding or removing users to/from the dedicated-admins group
- Scaling the cluster compute nodes
- Scaling the cluster load balancer
- Scaling the cluster persistent storage
- Upgrading the cluster

SRE-initiated changes that require manual intervention generally follow the below procedure:

- Preparing for Change
* Change characteristics are identified and a gap analysis against current state is performed.
* Change steps are documented and validated.
* Communication plan and schedule is shared with all stakeholders.
* CICD and end-to-end tests are updated to automate change validation.
* Change request capturing change details is submitted for management approval.
- Managing Change
* Automated nightly CI/CD jobs pick up the change and run tests.
* The change is made to Integration and Stage environments, and manually validated before updating the customer cluster.
* Major change notifications are sent before and after the event.
- Reinforcing the Change
* Feedback on the change is collected and analyzed..
* Potential gaps are diagnosed in order to understand resistance and automate similar change requests.
* Corrective actions are implemented.

Note: SREs consider manual changes a failure and this is only used as a fallback process.
