// Module included in the following assemblies:
//
// * assemblies/template-assembly.adoc

[id="proc-aws-vpn-propagation_{context}"]
= Enabling VPN route propagation

[role="_abstract"]
After you have set up the VPN connection, you must ensure that route propagation is enabled so that the necessary routes are added to the VPC's route table.

.Procedure

. Log in to the OSD AWS Account console, click *Services* -> *VPC* to access the VPC dashboard.
. Click on *Route Tables*.
. Select the private Route table associated with the VPC that contains your {product-title} cluster.
+
[NOTE]
====
On some clusters, there may be more than one route table for a particular VPC.
Select the private one that has a number of explicitly associated subnets.
====
. Click on the *Route Propagation* tab.
. In the table that appears, you should see the virtual private gateway you created previously. Check the value in the *Propagate column*.
.. If Propagate is set to *No*, click *Edit route propagation*, check the Propagate checkbox next to the virtual private gateway's name and click *Save*.

After you configure your VPN tunnel and AWS detects it as *Up*, your static or dynamic routes are automatically added to the route table.
