// Module included in the following assemblies:
//
// * assemblies/assembly-aws-direct-connect.adoc

[id="proc-aws-dc-hvif-private"]
= Creating a Private Direct Connect

[role="_abstract"]
A Private Direct Connect is created if the Direct Connect Virtual Interface type is Private.

.Procedure

. Log in to the OSD AWS Account Dashboard and select the correct region.

. From the AWS region, select *VPC* from the *Services* menu.

. Select *Virtual Private Gateways* from *VPN Connections*.

. Click *Create Virtual Private Gateway*.

. Give the Virtual Private Gateway a suitable name.

. Select *Custom ASN* and enter the *Amazon side ASN* value gathered previously.

. Create the Virtual Private Gateway.

. Click the newly created Virtual Private Gateway and choose *Attach to VPC* from the *Actions* tab.

. Select the *OSD Cluster VPC* from the list, and attach the Virtual Private Gateway to the VPC.

. From the *Services* menu, click *Direct Connect*. Choose one of the Direct Connect Virtual Interfaces from the list.

. Acknowledge the *I understand that Direct Connect port charges apply once I click Accept Connection* message, then choose *Accept Connection*.

. Choose to *Accept* the Virtual Private Gateway Connection and select the Virtual Private Gateway that was created in the previous steps.

. Select *Accept* to accept the connection.

. Repeat the previous steps if there is more than one Virtual Interface.
