// Module included in the following assemblies:
//
// * assemblies/assembly-aws-vpn.adoc

[id="proc-aws-vpn-config"]
= Configuring the VPN connection

[role="_abstract"]
You can configure an Amazon Web Services (AWS) {product-title} cluster to use a customer's on-site hardware VPN device using the following procedures.

.Prerequisites

* Hardware VPN gateway device model and software version, for example Cisco ASA running version 8.3. See the Amazon VPC link:https://docs.aws.amazon.com/vpc/latest/adminguide/Introduction.html#DevicesTested[Network Administrator Guide] to confirm whether your gateway device is supported by AWS.
* Public, static IP address for the VPN gateway device.
* BGP or static routing: if BGP, the ASN is required. If static routing, you must configure at least one static route.
* Optional: IP and Port/Protocol of a reachable service to test the VPN connection.

.Procedure

. Log in to the OSD AWS Account Dashboard, and navigate to the VPC Dashboard.

. Click on *Your VPCs* and identify the name and VPC ID for the VPC containing the {product-title} cluster.

. From the VPC Dashboard, click *Customer Gateway*.

. Click *Create Customer Gateway* and give it a meaningful name.

. Select the routing method: *Dynamic* or *Static*.

. If Dynamic, enter the BGP ASN in the field that appears.

. Paste in the VPN gateway endpoint IP address.

. Click *Create*.

. If you do not already have a Virtual Private Gateway attached to the intended VPC:
.. From the VPC Dashboard, click on *Virtual Private Gateway*.
.. Click *Create Virtual Private Gateway*, give it a meaningful name, and click *Create*.
.. Leave the default Amazon default ASN.
.. Select the newly created gateway, click *Attach to VPC*, and attach it to the cluster VPC you identified earlier.
