// Module included in the following assemblies:
//
// * assemblies/creating-your-cluster.adoc

//SF- Commenting out cluster privacy settings coming soon. ONLY FOR CCS!

[id="create-gcp-ccs-cluster_{context}"]
= Creating a GCP CCS Cluster

You can create a {product-title} cluster with a Customer Cloud Subscription (CCS) on Google Cloud Platform (GCP). With this subscription option, the cluster will be provisioned in a GCP account owned by you or your company. This allows you to pay GCP directly for public cloud costs, leveraging your existing relationship.

.Prerequisites

- Your GCP account has been configured for use with {product-title}.
- Your Google Cloud account has the necessary resource quotas and limits to support the desired cluster size.
- A GCP project has already been created. Note: The `projectID` length should not be more than 10 characters.
- An IAM service account in GCP called `osdCcsAdmin` with the following roles attached:
  * DNS Administrator
  * Organization Policy Viewer Owner
  * Project IAM Admin
  * Service Management Administrator
  * Service Usage Admin
  * Storage Admin
- A key has been created for your GCP service account and exported to a file named `osServiceAccount.json`.
- It is recommended that you have at least *Production Support* from GCP.
- To prevent potential conflicts, it is also recommended that no other resources are provisioned in the project prior to provisioning {product-title}.

.Procedure

. Log in to link:https://cloud.redhat.com/openshift[cloud.redhat.com/openshift].

. Click *Create Cluster* -> *Red Hat OpenShift Dedicated*.

. Select *Google Cloud* as your infrastructure provider.

. Select *Customer cloud subscription*. An informational dialogue window will open. Review the prerequisites for installing a GCP CCS cluster and click *Close*.

. Click *Browse* to locate and attach the *Service account JSON*.

. Enter your *Cluster name*.

. Select a *Region* and choose either a *Single zone* or *Multizone* availability.

. Select your *Compute node instance type* and the *Compute node count*. After your cluster is created, you can change the number of compute nodes in your cluster, but you can not change the worker node instance type.

. Optional: Expand *Edit node labels* to add labels to your nodes. Labels must be comma separated pairs in key=value format.

. The *Basic* Network configuration is selected by default. This setting creates a new VPC for your cluster using the default values.
If you want to configure your networking IP ranges,
// or set your cluster privacy
select *Advanced*. The following are the default ranges available for your networking IP ranges:

.. Node CIDR: 10.0.0.0/16

.. Service CIDR: 172.30.0.0/16

.. Pod CIDR: 10.128.0.0/14

.. Host Prefix: /23

+
[IMPORTANT]
====
CIDR configurations cannot be changed later. Confirm your selections with your network administrator before proceeding.
====

. Click *Create cluster*. The cluster creation process begins and will take about 30-40 minutes to complete.

The *Installing cluster* heading, under the *Overview* tab, will indicate the cluster is installing and you can view the installation logs from this heading. The *Status*
indicator under the *Details* heading will indicate when your cluster is *Ready* for use.
