// Module included in the following assemblies:
//
// * assemblies/assembly-creating-your-cluster.adoc
// * assemblies/assembly-quickstart-osd.adoc


[id="proc_create-cluster_{context}"]
= Creating a cluster

[role="_abstract"]
You can create a standard {product-title} cluster, which deploys in cloud provider accounts owned by Red Hat.

.Procedure

. Log in to link:https://cloud.redhat.com/openshift[OpenShift Cluster Manager (OCM)].

. Click *Create Cluster* -> *Red Hat OpenShift Dedicated*.

. Select a cloud infrastructure provider.

. Enter your *Cluster name*. The *Standard* billing model is selected by default.

. Select a *Region* and choose either a *Single zone* or *Multizone* availability.

. Select your *Compute node instance type* and the *Compute node count*. The number and types of nodes available to you depend
upon your {product-title} subscription.

. Optional: Expand *Edit node labels* to add labels to your nodes. Labels must be comma separated pairs in key=value format.

. Select the amount of *Persistent storage* and *Load balancers* you want set on the deployed cluster or accept the defaults.

. The *Basic* Network configuration is selected by default. This setting creates a new VPC for your cluster using the default values.
If you want to configure your networking IP ranges or set your cluster privacy, select *Advanced*.
+
[IMPORTANT]
====
Private clusters are only enabled for AWS at this time. If the cluster privacy is set to *Private*, you will not be able to access your cluster until you configure private connections in your cloud provider.
====
+
The following are the default ranges available for your networking IP ranges:

.. Node CIDR: 10.0.0.0/16

.. Service CIDR: 172.30.0.0/16

.. Pod CIDR: 10.128.0.0/14

.. Host Prefix: /23

+
[IMPORTANT]
====
CIDR configurations cannot be changed later. Confirm your selections with your network administrator before proceeding.
====

. Click *Create cluster*. The cluster creation process begins and will take about 30-40 minutes to complete.


The *Installing cluster* heading, under the *Overview* tab, will indicate the cluster is installing and you can view the installation logs from this heading. The *Status*
indicator under the *Details* heading will indicate when your cluster is *Ready* for use.
