:_module-type: REFERENCE
//Specify the module-type as either "CONCEPT, PROCEDURE, or REFERENCE"

// Module included in the following assemblies:
//
// * assemblies/planning-limits.adoc

[id="tested-cluster-maximums_{context}"]
= {product-title} tested cluster maximums

[role="_abstract"]
The following table specifies the maximum limits for each tested type in a cluster.

.Tested cluster maximums
[options="header",cols="50,50"]
|===
|Maximum type |4.6 tested maximum

|Number of nodes
|27

|Number of pods ^[1]^
|6,750

|Number of pods per node
|250

|Number of pods per core
|There is no default value.

|Number of namespaces ^[2]^
|1,000

|Number of pods per namespace ^[3]^
|6,750

|Number of services ^[4]^
|3,000

|Number of services per namespace
|3,000

|Number of back ends per service
|3,000

|Number of deployments per namespace ^[3]^
|3,000
|===
[.small]
--
1. The pod count displayed here is the number of test pods. The actual number of pods depends on the application’s memory, CPU, and storage requirements.
2. When there are a large number of active projects, etcd can suffer from poor performance if the keyspace grows excessively large and exceeds the space quota. Periodic maintenance of etcd, including defragmentation, is highly recommended to make etcd storage available.
3. There are a number of control loops in the system that must iterate over all objects in a given namespace as a reaction to some changes in state. Having a large number of objects of a given type in a single namespace can make those loops excessive and slow down processing the given state changes. The limit assumes that the system has enough CPU, memory, and disk to satisfy the application requirements.
4. Each service port and each service back end has a corresponding entry in iptables. The number of back ends of a given service impacts the size of the endpoints objects, which then impacts the size of data that is being sent all over the system.
--

In OpenShift Container Platform 4.6, half of a CPU core (500 millicore) is reserved by the system compared to previous versions of OpenShift Container Platform.
