:_module-type: CONCEPT
// Module included in the following assemblies:
//
// * assemblies/rosa-policy-process-security.adoc

[id="rosa-policy-change-management_{context}"]
= Change management

[role="_abstract"]
This section describes the policies about how cluster changes, configuration changes, patches, and releases are managed.

Cluster changes are initiated in one of two ways:

1. A customer initiates changes through self-service capabilities such as cluster deployment, worker node scaling, or cluster deletion.
2. Red Hat site reliability engineering (SRE) initiates a change through Operator-driven capabilities such as configuration, upgrade, patching, or configuration changes.

Change history is captured in the Cluster History section in the OpenShift Cluster Manager (OCM) Overview tab and is available to customers. The change history includes logs from the following changes:

- Adding or removing identity providers
- Adding or removing users to or from the `dedicated-admins` group
- Scaling the cluster compute nodes
- Scaling the cluster load balancer
- Scaling the cluster persistent storage
- Upgrading the cluster

The SRE-initiated changes that require manual intervention by the SRE generally follow this process:

- Preparing for change
* Change characteristics are identified and a gap analysis is performed against current state.
* Change steps are documented and validated.
* A communication plan and schedule are shared with all stakeholders.
* CI/CD and end-to-end tests are updated to automate change validation.
* A change request that captures change details is submitted for management approval.
- Managing change
* Automated nightly CI/CD jobs pick up the change and run tests.
* The change is made to integration and stage environments, and manually validated before updating the customer cluster.
* Major change notifications are sent before and after the event.
- Reinforcing the change
* Feedback on the change is collected and analyzed.
* Potential gaps are diagnosed to understand resistance and automate similar change requests.
* Corrective actions are implemented.

[NOTE]
====
The SREs only use manual changes as a fallback process because they consider manual intervention to be a failure of change management.
====

[id="rosa-policy-configuration-management_{context}"]
== Configuration management

The infrastructure and configuration of the {product-title} environment is managed as code. The SRE manages changes to the {product-title} environment using a GitOps workflow and automated CI/CD pipeline.

Each proposed change undergoes a series of automated verifications immediately upon check-in. Changes are then deployed to a staging environment where they undergo automated integration testing. Finally, changes are deployed to the production environment. Each step is fully automated.

An authorized SRE reviewer must approve advancement to each step. The reviewer cannot be the same individual who proposed the change. All changes and approvals are fully auditable as part of the GitOps workflow.

[id="rosa-policy-patch-management_{context}"]
== Patch management

OpenShift Container Platform software and the underlying immutable Red Hat CoreOS (RHCOS) operating system image are patched for bugs and vulnerabilities in regular z-stream upgrades. Read more about link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html/architecture/architecture-rhcos[RHCOS architecture] in the OpenShift Container Platform documentation.

[id="rosa-policy-release-management_{context}"]
== Release management

{product-title} clusters are upgraded weekly to ensure that the latest security patches and bug fixes are applied to {product-title} clusters.

Patch-level upgrades, also referred to as z-stream upgrades (for example, 4.3.18 to 4.3.19), are automatically deployed on Tuesdays. New z-stream releases are tested nightly with automated {product-title} integration testing and released only after they are validated in the OSD environment.

Minor version upgrades, also referred to as y-stream upgrades (for example, 4.3 to 4.4), are coordinated with customers by email notification.

Customers can review the history of all cluster upgrade events in their OCM web console on the Events tab.
