:_module-type: PROCEDURE
//Specify the _module-type as either "CONCEPT, PROCEDURE, or REFERENCE"

// Module included in the following assemblies:
//
// rosa-nodes/rosa-autoscale-nodes.adoc

[id="rosa-autoscaling_{context}"]
= Autoscaling nodes in an existing cluster

[role="_abstract"]
Configure autoscaling to dynamically scale the number of worker nodes up or down based on load. Autoscaling for worker nodes is configured in the machine pool definition if you are configuring an existing cluster.

[NOTE]
====
Additionally, autoscaling can be configured on the default machine pool when you create the cluster.
====

Successful autoscaling is dependent on having the correct AWS resource quotas in your AWS account. Verify resource quotas and request quota increases from the link:https://aws.amazon.com/console/[AWS console].

.Procedure
. To identify the machine pool IDs in a cluster, enter the following command:
+
[source,terminal]
----
$ rosa list machinepools --cluster=<cluster_name>
----
+
.Example output
+
[source,terminal]
----
ID        AUTOSCALING   REPLICAS    INSTANCE TYPE  LABELS    TINTS   AVAILABILITY ZONES
default   No            2           m5.xlarge                        us-east-1a
mp1       No            2           m5.xlarge                        us-east-1a
----
+
Decide which machine pool ID you want to configure.

. To enable autoscaling on a machine pool, enter the following command:
+
[source,terminal]
----
$ rosa edit machinepool --cluster=<cluster_name> <machinepool_ID> --enable-autoscaling --min-replicas=<number> --max-replicas=<number>
----
+
.Example
+
Enable autoscaling on a machine pool with the ID `mp1` on a cluster named `mycluster`, with the number of replicas set to scale between 2 and 5 worker nodes:
+
[source,terminal]
----
$ rosa edit machinepool --cluster=mycluster mp1 --enable-autoscaling --min-replicas=2 --max-replicas=5
----
. To disable autoscaling on a machine pool, enter the following command:
+
[source,terminal]
----
$ rosa edit machinepool --cluster=<cluster_name> <machinepool_ID> --enable-autoscaling=false --replicas=<number>
----
+
.Example
+
Disable autoscaling on the `default` machine pool on a cluster named `mycluster`:
+
[source,terminal]
----
$ rosa edit machinepool --cluster=mycluster default --enable-autoscaling=false --replicas=3
----
