include::_attributes/attributes-openshift-dedicated.adoc[]
[id="assembly-private-cluster"]
:context: assembly-private-cluster

= Configuring a private cluster

[role="_abstract"]
An {product-title} cluster can be made private so that internal applications can be hosted inside a corporate network. In addition, private clusters can be configured to have only internal API endpoints for increased security.

{product-title} administrators can choose between public and private cluster configuration from within the *OpenShift Cluster Manager* (OCM). Privacy settings can be configured during cluster creation or after a cluster is established.

include::modules/proc-enable-private-cluster-new.adoc[leveloffset=+1]

include::modules/proc-enable-private-cluster-existing.adoc[leveloffset=+1]

include::modules/proc-enable-public-cluster.adoc[leveloffset=+1]

[NOTE]
====
Red Hat Service Reliability Engineers (SREs) can access a public or private cluster through the `cloud-ingress-operator` and existing ElasticSearch Load Balancer or Amazon S3 framework. SREs can access clusters through a secure endpoint to perform maintenance and service tasks.
====
