include::_attributes/attributes-openshift-dedicated.adoc[]
[id="assembly-gcp-ccs"]
= Requirements for CCS on Google Cloud
:context: assembly-gcp-ccs

[role="_abstract"]
Red Hat recommends the usage of a Google Cloud (GCP) project, managed by the customer, to organize all of your GCP resources. A project consists of a set of users and APIs, as well as billing, authentication, and monitoring settings for those APIs.

It is a best practice for the {product-title} CCS cluster to be hosted in a GCP project within a GCP organization. The Organization resource is the root node of the GCP resource hierarchy and all resources that belong to an organization are grouped under the organization node. An IAM service account with certain roles granted is created and applied to the GCP project. When you make calls to the API, you typically provide service account keys for authentication. Each service account is owned by a specific project, but service accounts can be provided roles to access resources for other projects.

include::modules/proc-gcp-policy-ccs.adoc[leveloffset=+1]
include::modules/con-gcp-policy-iam.adoc[leveloffset=+1]
