include::_attributes/attributes-openshift-dedicated.adoc[]
[id="aws-ccs"]
= Requirements for CCS on AWS 
:context: aws-ccs

[role="_abstract"]
Red Hat recommends the usage of Organizations to manage multiple AWS accounts. The Organization, managed by the customer, hosts multiple AWS accounts. There is a root account in the organization that all accounts ultimately refer to in the account hierarchy.

It is a best practice for the {product-title} CCS cluster to be hosted in an AWS account within an AWS Organizational Unit. A SCP is created and applied to the Organizational Unit that manages what services the AWS sub-accounts are permitted to access. The SCP applies only to available permissions within a single AWS account for all sub-accounts within the Organizational Unit. You can also apply a SCP to a single account. All other accounts in the customer’s Organization are managed in whatever manner the customer requires. Red Hat SRE will not have any control over SCPs within the AWS Organization.


include::modules/aws-policy-ccs.adoc[leveloffset=+1]
include::modules/aws-policy-scp.adoc[leveloffset=+1]
include::modules/aws-policy-iam.adoc[leveloffset=+1]
include::modules/aws-policy-provisioned.adoc[leveloffset=+1]
