:system-module-type: PROCEDURE
// Module included in the following assemblies:
//
// *assemblies/aws-vpn.adoc

[id="aws-vpn-establishing"]
= Establishing the VPN Connection

[role="_abstract"]
After you have configured the VPN connection, you must establish the VPN connection.

.Procedure

. Log in to the OSD AWS Account console, click *Services* -> *VPC* to access the VPC dashboard.

. Click on *Site-to-Site VPN Connections*.

. Click *Create VPN Connection*.
.. Enter a unique name tag.
.. Select *Virtual Private Gateway* and select the previously created gateway from the drop-down list.
.. For the Customer Gateway, select *Existing*.
.. Select the *Customer Gateway ID* from the drop-down list.
.. Select either *Dynamic* or *Static* for your routing options.
... If the VPN will use BGP, select *Dynamic*.
... For *Static* routes, select the *Ip Version* and enter the Static IP CIDRs.
.. Optional: You can customize tunnel options. See, link:https://docs.aws.amazon.com/vpn/latest/s2svpn/modify-vpn-tunnel-options.html[Modifying Site-to-Site VPN tunnel options] in the AWS documentation.
.. Click *Create VPN Connection*.
.. Wait for VPN status to change to *Available*, approximately 5 to 10 minutes.
. Select the VPN you just created and click *Download Configuration*.
.. From the dropdown list, select the vendor, platform, and version of the customer gateway device, then click *Download*.
.. The *Generic* vendor configuration is also available for retrieving information in a plain text format.

[NOTE]
====
After the VPN connection has been established, be sure to set up Route
Propagation or the VPN may not function as expected.
====

[NOTE]
====
Note the VPC subnet information, which you must add to your configuration as the
remote network.
====
